### ISSUE TITLE
Source Maps Broken

### ISSUE THREAD

**Issue by robneu** [FlagshipWP/compass#29]
It looks like grunt-autoprefixer is removing the reference to our source map at the bottom of our compiled css files. This makes live editing in Chrome and newer versions of Firefox pretty lame.

**Comment by robneu** [comment]
I still haven't been able to get this working. It's been integrated into clean-css, but setting the souceMap option to true results in an error.

This is the config that I tried, along with a few others. There's an issue open about it: https://github.com/gruntjs/grunt-contrib-cssmin/issues/155 but so far there's been no response from the developers.

Here's the config that I attempted to get working, although I also tried a number of others :

```javascript
// https://github.com/gruntjs/grunt-contrib-cssmin
module.exports = {
	options: {
		report: 'gzip',
		sourceMap: true
	},
	style: {
		expand: true,
		cwd: '<%= paths.tmp %>',
		src: [
			'*.css',
			'!*.min.css'
		],
		dest: '<%= paths.tmp %>',
		ext: '.min.css'
	},
	vendor: {
		expand: true,
		cwd: '<%= paths.theme %>css/',
		src: [
			'*.css'
		],
		dest: '<%= paths.theme %>css/',
		ext: '.min.css'
	}
};
```
The error returned is `Error: ENAMETOOLONG, name too long` plus what appears to be a base64 encoded string of the CSS file.

If anyone can see where I've made a mistake or knows whats going on well enough to report the issue upstream, I'd really appreciate some help on it.

**Comment by GaryJones** [comment]
There's an option in one of the sourcemap-related packages to include the encoded original data in the source map, and that used to be false. Maybe it's now true for this package, which is why you're now seeing it?

**Comment by robneu** [comment]
Gary, it looks like that was part of the problem, but the source maps still don't work. On my local I've had source maps disabled in everything except Autoprefixer which is what was generating the error. 

With that removed, the styles are minified without any errors when the `sourceMap `option in `grunt-contrib-cssmin` set to true, but no map is generated.
