### ISSUE TITLE
Site logo theme support

### ISSUE THREAD

**Issue by ccgjosh** [FlagshipWP/compass#38]
I'm just curious why site-logo isn't enabled by default in header and functions? Seems most sites have a fancy logo nowadays, and the ability to hide the site-title/description is a checkbox away.

```php
<?php if ( current_theme_supports( 'site-logo' ) ) flagship_the_logo(); ?>
<?php hybrid_site_title(); ?>
<?php hybrid_site_description(); ?>
```
 
~~I see on flagshipwp.com you use a SVG background instead, which works great for modern browsers but no fallback for users stuck on IE8?~~
Nevermind just looked in theme.js and see the SVG tests, IETester is just whack. Looks great in IE9+

**Comment by robneu** [comment]
Since there hasn't been any more interest in this, I'm going to close it out for now. At some point we'll be setting up more example code for working with the features within Flagship Library which should make this a pretty quick thing to add if you'd like to do so.
