### ISSUE TITLE
Social icons missing in the authorbox?

### ISSUE THREAD

**Issue by nicksturkenboom** [FlagshipWP/compass#40]
Hi, I was wondering why there aren't any icons being output within the authorbox. In contrary, it only outputs the text span inside class. If I look at how the php code and the css classes are being described, it almost implies that there should be an icon there. However, within my stylesheet there's nothing found, nor is there a link towards the genericons in the author-box.php.

Could you give me any insights on this matter? Lies the problem within my setup or could it be that you have left this part out? I can't check anymore since it seems flagship removed the demo page.

**Comment by robneu** [comment]
I don't think icons were ever added into the default styles. They would need to be added to the genericons Sass partial and then styled to your liking. I'll go ahead and get some defaults added in there to make this a little easier to follow.

It's also worth noting that the social media profile meta is added by WordPress SEO, so if you haven't installed that you'll only be able to display your RSS feed info by default.
