### ISSUE TITLE
cssmin changes urls to tmp directory

### ISSUE THREAD

**Issue by djrmom** [FlagshipWP/compass#44]
I recently realized my style.min.css was ending up with all of the image urls being rewritten to tmp/images

Using rebase: false in cssmin options fixes this, although I have not been using it long enough to see if it might break something else.

**Comment by robneu** [comment]
This may be related to some recent changes in cssmin. I'll look into it today. Thanks for the report!

**Comment by robneu** [comment]
It looks like this was an issue in `grunt-contrib-cssmin` and has [been patched](https://github.com/gruntjs/grunt-contrib-cssmin/commit/1395dcc6acf4a4b410b0d9e589f1b7fe443b5035) on the latest version. The version of Compass in the develop branch is using the latest, but the master branch is not.

If you update to the newest version of `grunt-contrib-cssmin` via NPM and then re-build your theme, you shouldn't need to set rebase: false in your config. I use https://www.npmjs.com/package/npm-check-updates to handle npm updates in bulk.

Let me know if that doesn't work and I'll keep digging. :)

**Comment by djrmom** [comment]
Thanks Rob,  I didn't think to check to see if there was an update to cssmin.  I haven't tried it yet but from the commits, it looks like that would be the exact problem.
