### ISSUE TITLE
Stylesheet header disappearing

### ISSUE THREAD

**Issue by ccgjosh** [FlagshipWP/compass#45]
When running grunt and making edits to the scss files, style.css drops the header comments. When I stop grunt and run grunt build:css it comes back. Any idea on a fix for this?

**Comment by robneu** [comment]
I actually fixed this the other day but forgot to sync the changes. Sorry about that. Let me know if you run into any more issues after pulling in those changes.

Relevant commits: https://github.com/FlagshipWP/compass/commit/6c19a125026548cc285378924d2ec32c4727e846 and https://github.com/FlagshipWP/compass/commit/32338d0c82a072411bfd96e9558d2b697030f25a

**Comment by ccgjosh** [comment]
That did it thanks
