### ISSUE TITLE
Move to Node Sass

### ISSUE THREAD

**Issue by robneu** [FlagshipWP/compass#46]
I've been testing recently and I think Node Sass is finally at a point where we can safely move to it for the master branch of the project. This will remove one external dependency (Ruby) and two Bower dependencies (Bourbon and Neat).

I think the reduced complexity of setup and faster compiling are worth any minor features we might lose by using LibSass instead of Ruby Sass. Does anyone else have any thoughts on this? If there are no objections, I'll be moving ahead with this for the Compass 2.0.0 release which is due out fairly soon.

**Comment by GaryJones** [comment]
https://sass-compatibility.github.io/ shows where libsass and ruby sass still differ.

Libsass is currently on 3.1 and https://github.com/sass/libsass/wiki/The-LibSass-Compatibility-Plan shows that full compatibility isn't expected until libsass v3.4.

**Comment by robneu** [comment]
That's a nice resource. Thanks Gary. At first glance I don't see anything that would be blocking for us, and with how rapid development has been I don't think it will be too much longer before they're at least close to feature parity.

Personally, I don't mind trading some of the newer Sass features for better compiling performance and one less dependency. If anyone using Compass feels differently please make your case and I'll consider it.
