### ISSUE TITLE
Can you help me install?

### ISSUE THREAD

**Issue by axisdos** [FlagshipWP/compass#55]
Hey man, nice starter theme. So I got up to the point where we go to Themes page and upload the theme. Beyond that I have no idea what to do. Especially, installing other components to support the theme. Please help.

**Comment by robneu** [comment]
Thanks! In order for the theme to be useable you'll need to make sure all the dependencies are installed and the generated files are built. There's a rundown of the install procedure on our Wiki. 

There's also an installation walkthrough video but it's pretty out of date as it was done using the original release of Compass. I'll try to get another one recorded. Give [this page](https://github.com/FlagshipWP/compass/wiki/Installing-Compass) a read and then let me know if you get stuck in any particular area.

**Comment by axisdos** [comment]
My WP site is running on a shared Siteground hosting. None of the instructions from the given link are familiar with my knowledge. Please help. Thanks

**Comment by robneu** [comment]
It sounds like you're wanting to use the theme as-is? If that's the case, you can download this compiled version and install it normally. You can [download it here](http://flagshipwp.s3.amazonaws.com/compass-2.0.0.zip) and install it as-is.

It's not really intended to be used that way, but there's no reason you can't. If you want to use it as a development tool, you'll need to learn how to use the build tools.
