### ISSUE TITLE
Adding Kirki for theme settings

### ISSUE THREAD

**Issue by RajeebTheGreat** [FlagshipWP/compass#57]
I really don't know how you guys develop themes at FlagshipWP but many end-user prefer having theme settings for controlling different aspects of the theme. It's too much of pain to repeat writing the same code again and agin. That's where Compass theme excels as a good starter theme.

I came to know about this awesome project few days named Kirki ( https://github.com/reduxframework/kirki )  which extends WordPress customizer for adding settings field. Any chance we'll be seeing this integrated into Compass theme? I'm willing to help. That would be really awesome!

Thanks!

**Comment by robneu** [comment]
Sorry for the lack of response on this. I meant to reply to it a while back but it slipped my mind. There are no plans to integrate anything like Kiriki or Redux or any other options framework now or in the future. From a philosophy standpoint I don't agree with those projects, but it's also outside of what Compass is intended to do. 

If you or anyone else would like to include those or any other libraries, it should be fairly simple to do if they support Composer. If they don't, you could just manually integrate them or open a ticket with your library of choice about adding composer support.

Hope that clears things up a bit!

**Comment by RajeebTheGreat** [comment]
I closed it intentionally after realizing how stupid my request would have sound. I failed to understand that earlier :)

**Comment by robneu** [comment]
No worries, it wasn't stupid at all. Not asking questions when you're confused about something is 100x more stupid than any question could ever be. :)
