### ISSUE TITLE
Build Script Fails

### ISSUE THREAD

**Issue by adbutt** [FlagshipWP/compass#60]
Is there a paths problem? All bower component directories now sit in compass->assets->js->vendor 

The bower directory and relevant sub directories are not created eg.. bower/scss which causes the following to fail..

/*
HTML5 Reset
----------------------------------------------------------------------------- */
@import "../../bower/scss/wp-normalize";

**Comment by robneu** [comment]
I'm not sure I follow... are you saying that your `bower_components` folder is in the assets directory? If that's the case, that's not where the build scripts expects it to be, so that would cause all the copy commands related to bower to fail.

**Comment by adbutt** [comment]
No there isn't a bower_components folder. All of the components pulled down by bower go into the assets/js/vendor directory or one of the build scripts moves them and cleans the bower_components directory.

**Comment by robneu** [comment]
The `bower_components` directory is cleaned on a full build, so that's normal behavior. The default build config is set up to copy bower JS dependencies to `/assets/bower/js/concat` and then combine them on build. The default bower SCSS files are pulled into `/assets/bower/scss/` and then included in the main stylesheet.

What version of Compass are you using? I'll try to replicate your issue on my end.

**Comment by adbutt** [comment]
Hey Rob, 
Im using the latest version of compass v2.02 + PHP v5.5.24, Latest version of Node, Bower, composer & grunt 

-> Cloned the repo
-> cd'd into Compass
-> Ran NPM Install - (had to use sudo)
-> Ran Grunt Build

**Comment by adbutt** [comment]
Hey Rob, 
don't stress just tested on my main dev machine and it worked perfectly. I'll check sort the differences between my 2 machines.

**Comment by robneu** [comment]
Sounds good! If you do find something, please reopen the ticket and I'll try to figure it out on my end. Most of the most common issues people have had are related to [permissions](https://docs.npmjs.com/getting-started/fixing-npm-permissions) and npm cache.

Also, sometimes random things seem to go wrong with `npm install` and the only way to fix it is to remove `node_modules` and start over.
